from composio_agno import Action


gmail_tools_actions = [
    Action.GMAIL_FETCH_EMAILS, 
    Action.GMAIL_CREATE_EMAIL_DRAFT,
    Action.GMAIL_ADD_LABEL_TO_EMAIL,
    Action.GMAIL_CREATE_LABEL,
    Action.GMAIL_DELETE_DRAFT,
    Action.GMAIL_DELETE_MESSAGE,
    Action.GMAIL_FETCH_MESSAGE_BY_MESSAGE_ID,
    Action.GMAIL_FETCH_MESSAGE_BY_THREAD_ID,
    Action.GMAIL_GET_ATTACHMENT,
    Action.GMAIL_GET_CONTACTS,
    Action.GMAIL_GET_PEOPLE,
    Action.GMAIL_GET_PROFILE,
    Action.GMAIL_LIST_DRAFTS,
    Action.GMAIL_LIST_LABELS,
    Action.GMAIL_LIST_THREADS,
    Action.GMAIL_MODIFY_THREAD_LABELS,
    Action.GMAIL_MOVE_TO_TRASH,
    Action.GMAIL_REMOVE_LABEL,
    Action.GMAIL_REPLY_TO_THREAD,
    Action.GMAIL_SEARCH_PEOPLE,
    Action.GMAIL_SEND_EMAIL
    ]

calendar_tools_actions = [
    Action.GOOGLECALENDAR_CREATE_EVENT,
    Action.GOOGLECALENDAR_DELETE_EVENT,
    Action.GOOGLECALENDAR_DUPLICATE_CALENDAR,
    Action.GOOGLECALENDAR_FIND_EVENT,
    Action.GOOGLECALENDAR_FIND_FREE_SLOTS,
    Action.GOOGLECALENDAR_GET_CALENDAR,
    Action.GOOGLECALENDAR_GET_CURRENT_DATE_TIME,
    Action.GOOGLECALENDAR_LIST_CALENDARS,
    Action.GOOGLECALENDAR_PATCH_CALENDAR,
    Action.GOOGLECALENDAR_PATCH_EVENT,
    Action.GOOGLECALENDAR_QUICK_ADD,
    Action.GOOGLECALENDAR_REMOVE_ATTENDEE,
    Action.GOOGLECALENDAR_SYNC_EVENTS,
    Action.GOOGLECALENDAR_UPDATE_EVENT
]

weather_tools_actions = [Action.WEATHERMAP_WEATHER]

websearch_tools_actions = [
    Action.COMPOSIO_SEARCH_DUCK_DUCK_GO_SEARCH,
    Action.COMPOSIO_SEARCH_EVENT_SEARCH,
    Action.COMPOSIO_SEARCH_EXA_SIMILARLINK,
    Action.COMPOSIO_SEARCH_FINANCE_SEARCH,
    Action.COMPOSIO_SEARCH_GOOGLE_MAPS_SEARCH,
    Action.COMPOSIO_SEARCH_IMAGE_SEARCH,
    Action.COMPOSIO_SEARCH_NEWS_SEARCH,
    Action.COMPOSIO_SEARCH_SCHOLAR_SEARCH,
    Action.COMPOSIO_SEARCH_SEARCH,
    Action.COMPOSIO_SEARCH_SHOPPING_SEARCH,
    Action.COMPOSIO_SEARCH_TAVILY_SEARCH,
    Action.COMPOSIO_SEARCH_TRENDS_SEARCH
]


googledrive_tools_actions = [
    Action.GOOGLEDRIVE_ADD_FILE_SHARING_PREFERENCE,
    Action.GOOGLEDRIVE_COPY_FILE,
    Action.GOOGLEDRIVE_CREATE_FILE_FROM_TEXT,
    Action.GOOGLEDRIVE_CREATE_FOLDER,
    Action.GOOGLEDRIVE_DELETE_FOLDER_OR_FILE,
    Action.GOOGLEDRIVE_DOWNLOAD_FILE,
    Action.GOOGLEDRIVE_EDIT_FILE,
    Action.GOOGLEDRIVE_FIND_FILE,
    Action.GOOGLEDRIVE_FIND_FOLDER,
    Action.GOOGLEDRIVE_DOWNLOAD_FILE,
    Action.GOOGLEDRIVE_UPLOAD_FILE
]

google_maps_tools_actions = [
    Action.GOOGLE_MAPS_GET_DIRECTION,
    Action.GOOGLE_MAPS_GET_ROUTE,
    Action.GOOGLE_MAPS_NEARBY_SEARCH,
    Action.GOOGLE_MAPS_TEXT_SEARCH
]

slack_tools_actions = [
    Action.SLACK_SENDS_A_MESSAGE_TO_A_SLACK_CHANNEL,
    Action.SLACK_FETCH_CONVERSATION_HISTORY,
    Action.SLACK_LIST_ALL_SLACK_TEAM_CHANNELS_WITH_VARIOUS_FILTERS,
    Action.SLACK_FETCH_MESSAGE_THREAD_FROM_A_CONVERSATION,
    Action.SLACK_CREATE_A_REMINDER,
    Action.SLACK_LIST_USER_REMINDERS_WITH_DETAILS,
    Action.SLACK_DELETE_A_SLACK_REMINDER,
    Action.SLACK_SCHEDULES_A_MESSAGE_TO_A_CHANNEL_AT_A_SPECIFIED_TIME,
    Action.SLACK_ADD_REACTION_TO_AN_ITEM,
    Action.SLACK_REMOVE_REACTION_FROM_ITEM,
    Action.SLACK_SENDS_EPHEMERAL_MESSAGES_TO_CHANNEL_USERS,
    Action.SLACK_RETRIEVE_DETAILED_USER_INFORMATION,
    Action.SLACK_FIND_USER_BY_EMAIL_ADDRESS,
    Action.SLACK_GET_USER_PRESENCE_INFO,
    Action.SLACK_END_USER_DO_NOT_DISTURB_SESSION,
    ]

